### ISSUE TITLE
Discussion: Should SpectaQL break away from Swagger / OpenAPI?

### ISSUE THREAD

**Issue by newhouse** [anvilco/spectaql#111]
SpectaQL's roots come from [Dociql](https://github.com/wayfair/dociql), which comes from [Spectacle](https://github.com/sourcey/spectacle).

Spectaqle's docs state:
> Spectacle generates beautiful static HTML5 documentation from OpenAPI/Swagger 2.0 API specifications.

Because of this, there is a LOT of Swagger/OpenAPI specific stuff going on under the hood in SpectaQL:
- The GraphQL schema is converted in to a JSON Schema...
- There are many terms and handlebars templates that follow a JSON/Swagger naming and structuring convention...
- etc...

I've been developing SpectaQL for a while now, where I'm pretty confident that I want to throw away all of the legacy JSON/Swagger/OpenAPI internals as much as possible.

It's just a headache to squeeze things into the JSON Schema, and there are loopholes and caveats and workarounds starting to pop up more and more, and really there's not much more that I need other than an Introspection Query object and a GraphQL schema (one can be generated from the other, and vice versa).

There's also really not much that's exposed to the user anymore that is Swagger-esque. Only a few of the silly parts of the `config.yml` (`servers` and `info`) still resemble or come from the Swagger/OpenAPI...but they're very generic things that are stored in there.

Sure, there are some internals that still boil things down to Swagger, but they're private and not supposed to be touched by userland.

Shall I rip it all out and revamp things when I've got the time?

**Comment by AubSs** [comment]
Definitely, Swagger/OpenAPI don't seem to be useful for graphql.

By the way, you created a nice product!

**Comment by louisa-ba** [comment]
That would be awesome having a playground would be good too.

**Comment by mcwoodle** [comment]
I currently work with a custom fork of DociQL, and find it in general a pain, I'm not sure of how different spectacle is, but I think there's a strong need to create a simpler and more easily maintainable solution.

Have you started on anything for this idea? I want to get off DociQL and looking for an optimal solution.

**Comment by newhouse** [comment]
> Have you started on anything for this idea? I want to get off DociQL and looking for an optimal solution.

@mcwoodle 

There is an `rc-1.0.0` branch that I have been working a lot on lately. It's still a WIP but is getting closer: https://github.com/anvilco/spectaql/pull/232

It rips out pretty much all the swagger stuff and much of the DociQL stuff as well.

I'm still hoping to clean up some the API and names, as well as significantly clean up the HTML structure (organization, class names, etc) and accompanying CSS before releasing it so that I can avoid breaking changes later.

A lot has changed. What was it you were trying to do with your fork?

**Comment by newhouse** [comment]
This is now done in `1.0`!!!

**Comment by mcwoodle** [comment]
Thank you, @newhouse!

Our fork is for some custom internal integrations to add some extra links into the docs for finding source resolver info that's specific to a custom GQL server implementation we use. Nothing particularly useful for the community as a whole on its own.  However, a pluggable/extensible architecture could go a long ways in making it easier to extend v. fork in the future (if it doesn't exist yet?). Looking forward to checking out your work in 1.0!

**Comment by newhouse** [comment]
> Our fork is for some custom internal integrations to add some extra links into the docs for finding source resolver info that's specific to a custom GQL server implementation we use. Nothing particularly useful for the community as a whole on its own. However, a pluggable/extensible architecture could go a long ways in making it easier to extend v. fork in the future (if it doesn't exist yet?). Looking forward to checking out your work in 1.0!

@mcwoodle you might be able to accomplish what you want with:
- [Intro Items](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L316)
- Or, by creating a lightweight ["theme"](https://github.com/anvilco/spectaql/tree/main/examples/themes) of your own where you edit/add the appropriate Handlebars template file.

Good luck!
