### ISSUE TITLE
Missing fields on object input types

### ISSUE THREAD

**Issue by lensbart** [anvilco/spectaql#13]
Hello!

Thanks for making this — looks really nice.

I noticed that some fields were missing in the generated documentation; namely those that are on (nested) input object types.

Cheers!

**Comment by newhouse** [comment]
Hello @lensbart  and thank you for using SpectaQL!

Can you provide a bit more details?

Screenshots and (more importantly) some example data or SDL snippets that that I can use to identify and reproduce the error would be great!

**Comment by newhouse** [comment]
Hi @lensbart  - still hoping you can provide more details for me so I can try to fix things for you. Thanks!

**Comment by misternerd** [comment]
Hey @newhouse, I stumbled onto this issue as well. I hope it's the same thing, so I'll provide some information for how it looks on my end. The relevant part of the schema looks like this:

```
type Query {
	someQueryMethod(filters: FilterType, offset: Int = 0, limit: Int = 100): [ReturnType!]
}

"Comment for input type"
input FilterType {
	"Comment for input type field"
	someField: Boolean = false
}
```

Now, if I don't set `hideFieldsWithUndocumentedReturnType` in the config, the `FilterType` will still show up in the generated docs, but only with the comment above the type. The field list is completely empty.
However, if I set `hideFieldsWithUndocumentedReturnType: false`, then the field list gets filled, including comments, but without any type information. So the `someField` is shown like this:
```
someField - object    Comment for input type field
```

Please let me know if this is enough information for you to investigate or if you require a complete schema for validation.

**Comment by misternerd** [comment]
One additional thing I just noticed: Even though the left side marks the params as `object`, the right right hand side with demo data displays correct data. So for the boolean field from above, the right hand side contains the line `"someField": true`.
This is also true if the type of the field is another input object, then it's defined as `"otherInputTypeField": OtherInputType`

**Comment by newhouse** [comment]
@misternerd thanks for the details - much appreciated! This is probably enough to get me going. I will try to have a look later today.

**Comment by newhouse** [comment]
Fix is out and available in current `main` branch, or in version `0.2.0`. Thanks again!
