### ISSUE TITLE
Output for enums looks a bit wonky

### ISSUE THREAD

**Issue by lensbart** [anvilco/spectaql#14]
Hello again,

The generated documentation for enums seems overly verbose:

![afbeelding](https://user-images.githubusercontent.com/20876627/114597950-a48fa380-9c91-11eb-9345-ad8669855cdc.png)

Other than that, things look great!

**Comment by newhouse** [comment]
Hello @lensbart  and thank you (again!) for using SpectaQL!

If it's not too much trouble, can you provide me with an example JSON or SDL of your `Region` enum so that I can reproduce this on my side?

Thanks!

**Comment by lensbart** [comment]
Nothing out of the ordinary!

```graphql
enum Region {
  BRUSSEL
  VLAANDEREN
  WALLONIE
}
```

**Comment by newhouse** [comment]
Updated to look a bit nicer, and published in version `0.1.0`...thanks!
