### ISSUE TITLE
Intro Item with Multi-Line MarkDown-Enabled Content

### ISSUE THREAD

**Issue by ab-tools** [anvilco/spectaql#150]
It's great to have the option to add additional "x-introItems", but this seems pretty limited so far:
Based on my tests it only allows a single line of "description" for each additional intro item.

Would it be possible to allow multi-line, fully MarkDown-enabled (including bullet/numbered list and other MarkDown features) intro items instead of just single-line ones?

This would allow to describe important additional API-related parts (like a possibly required authorization) within these intro items.

Thanks in advance for considering
Andreas

**Comment by raoul-thill** [comment]
I think what you are looking for is the following:

```
    - title: Example
      description: |
        Now you can write your markdown followed by a list:
        * item1
          * sub-item1
          * sub-item2
        * item2
```

I use the multiple times in my `x-introItems` and this keeps the yaml readable.

**Comment by ab-tools** [comment]
Thanks a lot for your quick reply, Raoul!

Works perfectly as you wrote.
