### ISSUE TITLE
Schema Query/Mutation Description Ignored

### ISSUE THREAD

**Issue by ab-tools** [anvilco/spectaql#151]
Currently these descriptions of the `queryType` and `mutationType` seem to be completely ignored during documentation generation:

    {
        "data": {
            "__schema": {
                "queryType": {
                    "name": "ApiRequestQuery",
                    "description": "Description of query endpoint here.",
                    "kind": "OBJECT"
                },
                "mutationType": {
                    "name": "ApiRequestMutation",
                    "description": "Description of mutation endpoint here.",
                    "kind": "OBJECT"
                },
    [...]

It would be great if these descriptions could be included below the `Queries` and `Mutations` headlines in the documentation.

**Comment by newhouse** [comment]
Fixed in `0.9.4`

**Comment by ab-tools** [comment]
Much appreciated, @newhouse, works great now! :-)
