### ISSUE TITLE
Description Text Cut-Off Last Character

### ISSUE THREAD

**Issue by ab-tools** [anvilco/spectaql#153]
The last character (often just a `.`) is cut-off on every field description during report generation.

**Comment by newhouse** [comment]
I know that there's code to remove the trailing `.` character, specifically...but it should not be removing other characters.

Regardless, I think that behavior should be optional. Working on a change/fix.

**Comment by newhouse** [comment]
@ab-tools if you are able to provide a simple schema where a non `.` is removed, please let me know!

**Comment by ab-tools** [comment]
Thanks a lot for looking into that, @newhouse:
I think you are right that all occurrences of this issue I found were about a trailing `.`, I just could not imagine this would be on purpose, so I thought it was just the last character that got removed. ;-)

But yes, please make that optional (or remove this "feature" completely).

Not sure when this would make sense actually?
Even in the documentation link as an example on GitHub I think it's pretty strange that the last description sentence of many descriptions there is missing a `.` at the end, e. g. here:
https://www.useanvil.com/docs/api/graphql/reference/#operation-signer-Queries

**Comment by newhouse** [comment]
I can't remember why I put it i there, honestly, but at this point in time it does not seem desirable to me. Fix coming soon.

**Comment by newhouse** [comment]
I can't remember why I put it i there, honestly, but at this point in time it does not seem desirable to me. Fix coming soon.

**Comment by newhouse** [comment]
Fixed in `0.9.4`. There is now an option for it.
