### ISSUE TITLE
Clicking on a jump-link and going back

### ISSUE THREAD

**Issue by knotenpunkt** [anvilco/spectaql#160]
hey,

if i click on a jump link in the doc, and then on the going-back-button in the browser, then nothing happens. but the expected behaviour should be jumping back to the position where i can see the link

**Comment by newhouse** [comment]
Hi @knotenpunkt and thanks for using SpectaQL!

I'm not sure that I 100% follow you? Can you be a little more specific so that I can replicate things?

In Chrome, for me, when I click around and then use the `back` button, things work as I'd expect them to. But perhaps I'm doing something differently than you are, or I'm using a different browser?

**Comment by knotenpunkt** [comment]
No i dont use SpectaQL yet, still i use DociQL, but i want to to move to SpecaQL, because ....... yeah i think you know, DociQL is not very usable, i did there some hacks in it, to getting a better result, but i think SpectaQL did more to get a better output.

So to the mai problem here in the issue:

Yeah i use also Chrome, and the links i the body don't have the jump-back possibility.

if you go to that position:

> Fetches the currently logged in user. When used in an API context, this will return your API user. The currentUser query is useful to fetch objects in your organization. e.g. your Organization, its Welds, etc
> Returns a User

and if you click then on >>>User<<<, then you cant jump back by clicking the back-button

**Comment by newhouse** [comment]
> No i dont use SpectaQL yet, still i use DociQL, but i want to to move to SpecaQL, because ....... yeah i think you know, DociQL is not very usable, i did there some hacks in it, to getting a better result, but i think SpectaQL did more to get a better output.

DociQL was a really great base/starting point, and this project would not exist without it...but I'm glad you like the work I've done in SpectaQL!

> if you go to that position:
> 
> > Fetches the currently logged in user. When used in an API context, this will return your API user. The currentUser query is useful to fetch objects in your organization. e.g. your Organization, its Welds, etc
> > Returns a User
> 
> and if you click then on >>>User<<<, then you cant jump back by clicking the back-button

OK, looks like you're using our own documentation as the example. If I actually _click_ on the `User` Query link in the lefthand nav area, I end up with a URL like this in the browser: `https://www.useanvil.com/docs/api/graphql/reference/#operation-currentuser-Queries`. Then if I click on the `User` reference link in `Returns a User`, I am able to use the "back button" in Chrome to get back to the `User` Query...as expected.

I guess you're referring to when you scroll along (without clicking) the anchor tags don't adjust with you? I can look into that and see if it's easily adjusted.

**Comment by newhouse** [comment]
@knotenpunkt

The best I can do for you is allow you to turn on the [`deepLinking` feature in the `Traverse` code](https://github.com/anvilco/spectaql/blob/main/app/javascripts/traverse.js#L48) if you so choose, by allowing arbitrary JavaScript of your choosing to be bundled up with your build.

This PR allows for this behavior: https://github.com/anvilco/spectaql/pull/169

How it would work:
1. Create a JS file somewhere (e.g. `addtional.js`)
2. Add the following statement to that JS file that will adjust the `Traverse` options defaults, turning on `deepLinking`: `Traverse.defaults.deepLinking = true;`
3. Provide the path to the above JS file either via the CLI `--additional-js-file` option, or in your configuration YAML via the `additionalJsFile` key, under the `spectaql` object (see the PR for more of an idea).

**Comment by knotenpunkt** [comment]
> I guess you're referring to when you scroll along (without clicking) the anchor tags don't adjust with you? I can look into that and see if it's easily adjusted.

Ah yeah, that would be nice too having that.


>  I end up with a URL like this in the browser: https://www.useanvil.com/docs/api/graphql/reference/#operation-currentuser-Queries. Then if I click on the User reference link in Returns a User, I am able to use the "back button" in Chrome to get back to the User Query...as expected.

Ah i see, you did there something else then i did.

I opened the page from you and then i don't navigate to the currentUser-Query-operation, but i scrolled a little bit down getting/seeing it. 

And then i did what you described next, i clicked on that user field and jumping back to the position i scrolled before doesn't work.

Maybe you have to save before the jump the currently scroll position getting back after clicking the back button then

**Comment by newhouse** [comment]
It all seems to work for me, and if you'd like the history to change as you scroll around you can use the approach mentioned in [this comment](https://github.com/anvilco/spectaql/issues/160#issuecomment-983091394).

Closing this for now.
