### ISSUE TITLE
Handle deprecated fields

### ISSUE THREAD

**Issue by mscolnick** [anvilco/spectaql#18]
It would be great to show deprecation info when fields are deprecated. It looks like it is something that is [returned from introspection](https://github.com/anvilco/spectaql/blob/39bd6d933be950882b356dc94b4dc1ffa53e7ba2/examples/data/introspection-with-metadata.json#L39)

**Comment by newhouse** [comment]
HI @mscolnick and thanks for writing in!

You're correct that this information is in the Introspection Query results as long as it's in your schema. I also think this would be a nice thing to add into SpectaQL. I'm going to think about it a bit and tinker around with how it might work. Stay tuned, please.

**Comment by newhouse** [comment]
@mscolnick this is published in version `0.4.0`!
