### ISSUE TITLE
Unclear how to change CSS of generated documentation

### ISSUE THREAD

**Issue by mbreslow** [anvilco/spectaql#193]
Hi. I'm using the NPM installed package (not the git clone). I'm unable to figure out how to add CSS overrides so I can control the look and feel of the generated docs.

**Comment by newhouse** [comment]
@mbreslow I'm sorry to report that for now, via the `npm`/`npx` route, this is going to tough.

I'm in the middle of re-writing a lot of SpectaQL and tidying up a bunch of spots (like this) that I'm not happy with as new `1.0` release...SpectaQL is still in `0.x`, as you can see. So if you can wait a bit (a few weeks, probably yet), that's an option.

While there are probably several ways to get this done now, here are 2 options:
1) Overwrite the entire CSS file in SpectaQL's output
- In the output of your build, find the `stylesheets/spectaql.min.css` file that's being generated. This file's content should not change from run-to-run unless you have changed some significant options in between runs. 
- Use that CSS file as the starting point for the CSS that you ultimately want.
- Adjust the CSS as necessary and save it somewhere else it won't get overwritten.
- As part of your SpectaQL process, copy your new customized CSS to `/path/to/output/stylesheets/spectaql.min.css`, and it will be found/used in the HTML rendering.

2) If you think your changes will play nicely with the way Foundation is set up and/or want the power of SCSS, you can:
- edit the `full.scss` (or `basic.scss`) files in `/path/to/node_modules/spectaql/customizations/scss/<full or basic>.scss`
- It's probably better if you (similar to the above solution) create your own `xxx.scss` file and (as part of your build process) copy it over to the path mentioned in the above step _before_ running SpectaQL.

Very sorry that the ergonomics of this still are not great for now. I'm working on them.

**Comment by JeromeErasmus** [comment]
If I understand this right, what you are suggesting as a temporary workaround is to override the core model code to customize the scss files?

**Comment by newhouse** [comment]
> If I understand this right, what you are suggesting as a temporary workaround is to override the core model code to customize the scss files?

@JeromeErasmus That's _an_ option. The less invasive/icky one is to overwrite the `spectaql.min.css` in your output directory with a custom CSS file you've created. I suggested using the default generated CSS as a starting point. It's not ideal, I know.

I am working on a pattern for this that feels right before I commit to exposing something in the API that I will regret.

**Comment by newhouse** [comment]
This is now supported in `0.15.0`, thanks to changes in [this PR](https://github.com/anvilco/spectaql/pull/237), via the [`additionalCssFile`](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L14) YAML config option, or via the [`--additional-css-file`](https://github.com/anvilco/spectaql/blob/main/bin/spectaql.js#L59) CLI option.

Closing for now...
