### ISSUE TITLE
[Question] How to add Subscription into Documentation?

### ISSUE THREAD

**Issue by aryawpratama** [anvilco/spectaql#196]
How to introspect Subscription? I have several endpoint in Subscription but it won't appear

![image](https://user-images.githubusercontent.com/75900371/150303599-18c2a137-daad-48c2-8029-c7a46f3dc005.png)
![image](https://user-images.githubusercontent.com/75900371/150303810-2919b67c-c1cc-4390-a5ca-58d6cf9dbab3.png)

**Comment by newhouse** [comment]
@aryawpratama Unfortunately, for the moment, this is not possible. I'll do my best to add it ASAP to either `0.x` or `1.x` versions. In the meantime, I will keep this issue open as a reference.

**Comment by aryawpratama** [comment]
@newhouse Thank you!

**Comment by louisa-ba** [comment]
I would be super keen on this feature :)

**Comment by newhouse** [comment]
I have added support for this in `1.0.0`...but it's not "out" yet:
https://github.com/anvilco/spectaql/pull/225

**Comment by newhouse** [comment]
This is now out in `1.0` as part of the default theme.
