### ISSUE TITLE
feature request: environment variable usage in config.yml

### ISSUE THREAD

**Issue by itizarsa** [anvilco/spectaql#197]
I would like to raise a feature request to use the environment variable in config.yml.

By the way, spectaql is really great. Thanks a lot!

**Comment by newhouse** [comment]
Coming out in 2.0 soon.

**Comment by newhouse** [comment]
This is now supported/fixed in `v2`.

**Comment by iamshadmirza** [comment]
> This is now supported/fixed in `v2`.

Can you provide an example on how to use env variable in config file? @newhouse
