### ISSUE TITLE
Adding Markdown file to x-introItems

### ISSUE THREAD

**Issue by sjtommylee** [anvilco/spectaql#206]
New to spectaql, and really enjoying the experience so far. 

Is there a way to add markdown files in the description of the x-introItems? 
I have some copy for the documentation that I would like to keep in a separate file, and read from it instead of having the raw text inside of the description. 

`
x-introItems: 
   - title: some title
   - (import MD with copy file here)
`

**Comment by ledburyb** [comment]
I'm also wanting to use something like this, I had a go at a PR but I'm not familiar enough with the codebase to work it all out.

**Comment by newhouse** [comment]
Will be supported in `1.0.0`, which is not out yet.

Fixed via https://github.com/anvilco/spectaql/pull/227
