### ISSUE TITLE
Syntax Error: Unexpected <EOF>

### ISSUE THREAD

**Issue by ccc-zachary-leigh** [anvilco/spectaql#211]
Hello. I am testing this package out with the following config and schema file:
```yml
introspection:
  schemaFile: ./sdl.gpl
```

```graphql
type Query {
  staff(staffId: Int!): Staff
}

"""
Our fearless staff
"""
type Staff {
  """
  Staff ID
  """
  staffId: Int

  """
  Staff first name
  """
  firstName: String

  """
  Staff last name
  """
  lastName: String
  email: String
  fightsBearsAndWins: Boolean
}
```
When running `npx spectaql config.yml` I get the following error:
```
Syntax Error: Unexpected <EOF>.
```
Even when the schema file is empty the error occurs.

On version 0.12.0 on Ubuntu. npm version is 6.14.6.

**Comment by pylipp** [comment]
It seems that spectaql does not recognise the `.gpl` file extension (might be a typo anyways?). This config works on my end:

```
introspection:
  schemaFile:
    - sdl.gql
info:
  x-swaggerUrl: https://www.foo.bar
```

**Comment by ccc-zachary-leigh** [comment]
Thank you @pylipp, I think the typo was the issue. Working now. Feeling pretty stupid :sweat:

**Comment by newhouse** [comment]
> Thank you @pylipp, I think the typo was the issue. Working now. Feeling pretty stupid 😓

Don't feel stupid! It's a pretty worthless/unhelpful error message. I'll see if I can't detect this scenario and provide a more useful error message. Re-opening for now.

**Comment by newhouse** [comment]
Thank you @pylipp for your help on this one!

**Comment by ccc-zachary-leigh** [comment]
Thank you @newhouse !

**Comment by newhouse** [comment]
Will be supported in `1.0.0` when it comes out.

**Comment by newhouse** [comment]
This is now out in `1.0.0`
