### ISSUE TITLE
How do you blacklist queries?

### ISSUE THREAD

**Issue by AxelUlmestig** [anvilco/spectaql#230]
According to the list of features you can
> Supports blacklisting entire areas (e.g. "don't show Mutations") and 1-off blacklisting.

I would like to hide some queries in the documentation. I can't find any other reference to how you do it.

Thank you :)

**Comment by newhouse** [comment]
Hi @AxelUlmestig and thanks for using SpectaQL!

All queries can be hidden via [this](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L147) or [this](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L150) config option.

What you probably want to do is hide individual queries, and that's done via providing the appropriate "metadata" to SpectaQL. The documentation for it is here: https://github.com/anvilco/spectaql#metadata
