### ISSUE TITLE
CSS customization issues

### ISSUE THREAD

**Issue by JeromeErasmus** [anvilco/spectaql#236]
Hi guys,

Would anyone here be able to provide a working example of the SCSS override folder hierarchy please?

Im trying to do a simple thing to add one custom CSS class to compile with the rest of the scss files

**Comment by newhouse** [comment]
Can you provide a simple example of what you're trying to add?

I mean, I can guess at the idea, but rather than guess it'd be better to confirm the exact use case you mean. I'm trying to understand more what people are exactly trying to do.

**Comment by newhouse** [comment]
This is now supported in `0.15.0`, thanks to changes in [this PR](https://github.com/anvilco/spectaql/pull/237), via the [`additionalCssFile`](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L14) YAML config option, or via the [`--additional-css-file`](https://github.com/anvilco/spectaql/blob/main/bin/spectaql.js#L59) CLI option.

Closing for now, but let me know if you have any more questions.
