### ISSUE TITLE
Examples from graphql-scalar have wrong behaviour

### ISSUE THREAD

**Issue by KeGaWeb** [anvilco/spectaql#265]
Hi there ! 

I just updated to last version (1.0.5), and now I'm facing issues with scalar examples.
Examples are shown as Array, meaning with a String scalar it shows: `["abc123", "xyz789"]`.
I expected it to work just as `examples` in the metadata files : one random value being used during generation.

NB: this doesn't occur when `graphqlScalarExamples: false`.

**Comment by newhouse** [comment]
Should be fixed in `1.0.6`...sorry/thanks!
