### ISSUE TITLE
Scroll-spy doesn't work correctly on Firefox

### ISSUE THREAD

**Issue by kirudenk** [anvilco/spectaql#298]
Hello!
Apparently Firefox is treating differently `scrollIntoView` thus it causes a bug when selecting one of the bottom elements in the nav view page gets scrolled even further down from that element as if there is a recursive loop.
Thank you!

**Comment by benogle** [comment]
Hey @kirudenk I was able to reproduce and it's a pretty simple fix (https://github.com/anvilco/spectaql/pull/299). We'll have a new release out soon with the fix.

**Comment by newhouse** [comment]
@kirudenk should be fixed in `1.0.14`...
