### ISSUE TITLE
Weird scrolling behavior makes docs unusable on Mac with Firefox

### ISSUE THREAD

**Issue by sgabler-solytic** [anvilco/spectaql#313]
When I use the example docs on https://www.useanvil.com/docs/api/graphql/reference/, the scrolling behavior is very weird for me, making the page basically unusable, or at least very frustrating.

I recorded a video of the behavior:

https://user-images.githubusercontent.com/55686147/164265989-10bbdd42-45fe-4346-aa91-4240a5bbc079.mov

What I'm doing:
- at the beginning of this video I'm scrolling up with my mouse wheel. I don't use a touchpad.
- at some point I click on a different menu item and then start scrolling up again

My specs:
- MacOs Big Sur (11.4)
- Firefox 100.0 (Developer Edition)
- Mouse: Logitech G305

It works on Chromium Version 103.0.5015.0 (Developer Build) (x86_64), so I think this might be a Firefox specific thing.

I don't have a windows machine here, so I can't test it there unfortunately.

**Comment by newhouse** [comment]
@sgabler-solytic thanks for pointing this out!

Actually, this behavior has been [fixed](https://github.com/anvilco/spectaql/pull/299) in SpectaQL `1.0.14`...we just have not rolled that out to our own site yet!

Going to close this for now as we'll get it fixed ASAP.

Again, thanks for reporting, but it should not be a problem with sites generated by the current version of SpectaQL.

**Comment by benogle** [comment]
Hey @sgabler-solytic, the fix is out on our live docs. Thanks for the report!

**Comment by sgabler-solytic** [comment]
Nice. Now it works perfectly on my machine with Firefox. Thank you!
