### ISSUE TITLE
Problem with sticky/fixed Navigation bar with scroll (Bug)

### ISSUE THREAD

**Issue by albala99** [anvilco/spectaql#322]
- When we add a custom sticky/fixed Navigation bar 
- on clicking the links on the left Sidebar
- it scrolls to the id linked but Navigation bar overlaps above the Title
- Refer the video

https://user-images.githubusercontent.com/61052566/165499306-a8304743-2e71-43cb-a935-cba1ae18ee56.mov

**Comment by newhouse** [comment]
Hello @albala99 - just to confirm, this is a problem you're seeing on Anvil's website, right? But it's not a problem generally with SpectaQL when _you_ use it?

**Comment by albala99** [comment]
Hi @newhouse  , the same is happening if i use a custom nav bar in spectaql

**Comment by newhouse** [comment]
@albala99  In SpectaQL `1.2.0` you can now set the [`scrollPaddingTopPx`](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L39) option to adjust as necessary.

Can you try this and report back?

**Comment by newhouse** [comment]
Closing  as I think this is fixed.
