### ISSUE TITLE
Multiple schemas from folder

### ISSUE THREAD

**Issue by Munoon** [anvilco/spectaql#323]
As a user, I want to specify a folder, from which I want spectaql to load schema. It is uncomfortable for me to specify each GraphQL schema file by hand in the config file.

Here is an example: \
**config.yml**
```yaml
introspection:
  schemaFile: ./graphql/
```

**Files schema**
* config.yml
* graphql
  * graphql_schema_1.graphqls
  * graphql_schema_2.graphqls
  * graphql_schema_3.graphqls
  * ...

**Comment by Munoon** [comment]
Currently it can be implemented by using following introspection js script:
```javascript
const graphql = require("graphql");
const loadFiles = require("@graphql-tools/load-files");
const merge = require("@graphql-tools/merge");

const files = loadFiles.loadFilesSync("./graphql");
const mergeTypeDefs = merge.mergeTypeDefs(files);
const printedTypeDefs = graphql.print(mergeTypeDefs);
const schema = graphql.buildSchema(printedTypeDefs);
module.exports = graphql.introspectionFromSchema(schema);
```

**Comment by newhouse** [comment]
@Munoon you should already be able to pass a directory/glob to the `schemaFile` value and it should work. Something like `./graphql/*.gql`.

Any glob supported by https://www.graphql-tools.com/docs/api/modules/load_files_src should work.

**Comment by Munoon** [comment]
@newhouse it works only with schemas in specific folders. What if I also want to include sub-folders?

For example, I have multiple schemas in following folders:\
./graphql/schema-1.gql \
./graphql/schema-2.gql \
./graphql/sub/schema-3.gql \
./graphql/sub/schema-4.gql

Also, maybe it will be useful to add an example of the passing directory to `schemaFile` in the documentation.

**Comment by newhouse** [comment]
You'll have to try reading up on different glob patterns that are supported by that library. Typically something like `./graphql/**/*.gql` will work.

**Comment by Munoon** [comment]
Thank you, that’s really work!
