### ISSUE TITLE
Custom logo doesn't work in latest version

### ISSUE THREAD

**Issue by mielvds** [anvilco/spectaql#326]
Hi!

I use 

```
spectaql:
  logoFile: ...
```

But since the last update, that logo is no longer picked up. Did the key change, or is something else up?

**Comment by newhouse** [comment]
Hi @mielvds I believe the logo is working as intended, at least as far as I can tell. Are you on the latest version of SpectaQL?

The only thing that's perhaps changed is that if the path you provide is not an absolute path (i.e. it does not start with `/abs/path/to/file`) and is instead a relative path (e.g. `./path/to/file`), then the relative path is considered to be from the `cwd`...and not the root of the project.

Can you provide more details about your directory and file structure, the value you actually used in the config, and the location and command you are executing spectaql with?

**Comment by mielvds** [comment]
Hi @newhouse, I did some more digging and it's a result of the new styling. My logo is SVG and is rendered with size 0x0 in firefox. Chrome and Safari do show it, but it's very tiny. 

Switching off the following CSS rule fixes the issue:

```
#spectaql #logo img {
	max-height: 18px;
}
```

**Comment by newhouse** [comment]
@benogle any thoughts on this one? I remember an SVG being a problem for me at one point, too.

**Comment by benogle** [comment]
Hey @mielvds, what version of spectaql are you using? It renders an SVG fine in firefox for me. Can you attach the SVG you are using?

We can bump up the max-height, but this is something that likely needs to be adjusted in most people's applications anyway.

**Comment by newhouse** [comment]
OK, changed the option to be [`logoHeightPx`](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L14) and this should work in both FFox and Chrome.
