### ISSUE TITLE
Header tags opening and closing tags are not matching

### ISSUE THREAD

**Issue by CarpenterJoseph** [anvilco/spectaql#339]
Closing header tags are sometimes h5

![Screen Shot 2022-05-05 at 13 24 33](https://user-images.githubusercontent.com/22171893/166913635-8d7743d2-0a18-4257-b143-a961e27c156d.png)
![Screen Shot 2022-05-05 at 13 25 52](https://user-images.githubusercontent.com/22171893/166913858-868264a5-a7ce-470f-a655-250d232d414d.png)

**Comment by newhouse** [comment]
Thanks @CarpenterJoseph for checking out SpectaQL! One of these was recently fixed (but not published), but the other one is new to me, so thanks! Will fix.
