### ISSUE TITLE
Running the current version 1.1.3 fails

### ISSUE THREAD

**Issue by jocrau** [anvilco/spectaql#351]
Thanks for the rapid turnaround on the two PRs! More to come :-)

Unfortunately, the [current version](https://www.npmjs.com/package/spectaql/v/1.1.3) `1.1.3` fails with

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './dist'
```

**Comment by newhouse** [comment]
Can you try `1.1.4`? That was a borked publish.

**Comment by jocrau** [comment]
Version `1.1.4` works as expected, thanks!
