### ISSUE TITLE
Mutations with unions do not have a query segment in example

### ISSUE THREAD

**Issue by mengledowl** [anvilco/spectaql#405]
Our mutations return a union, eg:

```graphql
union MutationResponse = Error | Success

type Error {
  # ...
}

type Success {
  # ...
}

type Mutation {
  myMutation: MutationResponse!
}
```

The issue we're running into is that in the generated docs, the example query does NOT have the query segment. For example, for the above, it might generate something like so:

```graphql
mutation myMutation {
  myMutation
}
```

Whereas what I would expect would be something more like:

```graphql
mutation myMutation {
  myMutation {
    ...on Error {
      ...error
    }
    ...on Success {
      ...success
    }
}
```

This is unfortunately a major blocker for us as the examples produced are not actually valid examples (the examples would result in a syntax error from the server). I had hoped to override them myself but there doesn't appear to be any way to hook into this the way that you can hook into the responses being generated using the `dynamicExamplesProcessingModule` config option, unless I'm missing something?

(Side note: I'm pretty sure this same problem would apply to queries, but I don't have any queries returning a union so I'm not 100% certain).

**Comment by newhouse** [comment]
Adding support in https://github.com/anvilco/spectaql/pull/407

**Comment by newhouse** [comment]
Added in v`1.4.0`

**Comment by mengledowl** [comment]
@newhouse That was blazing fast turnaround - thank you! Verified working in 1.4.0
