### ISSUE TITLE
Dynamic links broken when using `info.x-introItems.file`

### ISSUE THREAD

**Issue by mengledowl** [anvilco/spectaql#416]
Creating a dynamic link to some part of the GraphQL documentation (eg. a type, query, etc) does not work when using the `file` option:

```yml
info:
  x-introItems:
    - title: Works
      description: Link here works [myQuery]({{Queries.myQuery}})
    - title: Does Not Work
      file: ./my-markdown-file.md
```

my-markdown-file.md
```md
Link here does **NOT** work: [myQuery]({{Queries.myQuery}})
```

`description` variant correctly links to `/index.html#query-myQuery`, whereas the `file` variant doesn't seem to parse, as it attempts to link to `/{{Queries.myQuery}}`

**Comment by newhouse** [comment]
Fixed in v `1.4.1`
