### ISSUE TITLE
Add examples to add metadata for ENUM and INTERFACE

### ISSUE THREAD

**Issue by gonzalezzfelipe** [anvilco/spectaql#436]
On the examples folder there is an enum and an interface on the schema, but they are not modified by the `metadata.json`. Is it possible to undocument certain elements of an interface and of enum? I've been trying unsuccessfully for the last couple of hours to do so. I'd be happy to make the PR to add the examples, if it is possible.

**Comment by newhouse** [comment]
This is out in `main` and v`1.5.1`
