### ISSUE TITLE
Setting Boolean, String as `undocumented` causes compilation issues

### ISSUE THREAD

**Issue by felixvd** [anvilco/spectaql#438]
I would like to hide the basic types in the generated doc, and this works fine for `Int` and `Float`. However, setting `Boolean` or `String` as `"undocumented": true` under `SCALAR` causes compilation to fail.

To reproduce, change the example `metadata.json` to e.g.:

```json
"SCALAR": {
  "Boolean": {
    "documentation": { "undocumented": true}
  }
},
```

**Comment by newhouse** [comment]
@felixvd can you please provide the error you are seeing?

I am unable to reproduce the error locally. Perhaps you just have a minor JSON syntax error? That file is `.json` and not `.js`, so you can't have unnecessary commas, and things like that, or you will get a parsing error.

**Comment by felixvd** [comment]
Sadly I can't reproduce this myself anymore. I only remember that the JSON was fine, and the error occurred later. It might have been an issue with my build. I will close for now. Sorry for the noise.
