### ISSUE TITLE
List Subscriptions immediately under Mutations

### ISSUE THREAD

**Issue by BoilerTom90** [anvilco/spectaql#442]
Currently, Queries and Mutations are listed as Operations are listed at the top of the left sidebar.  Subscriptions are listed at the bottom after all of the types in their own section labeled Subscriptions.   I think it makes more sense for the subscriptions section to be moved up right under the Operations section, or better yet, just consider a Subscription an Operation. Similar to the way the default graphiql playground lists "root" types:

![image](https://user-images.githubusercontent.com/17208255/181636697-267d9e43-d0e1-4a45-984c-ce06a22d1404.png)

**Comment by newhouse** [comment]
Related to https://github.com/anvilco/spectaql/issues/418

**Comment by BoilerTom90** [comment]
Thanks for the consideration!

**Comment by newhouse** [comment]
I think perhaps this should be an "option" that can be passed to the default included themes.

**Comment by newhouse** [comment]
This will be the default in 2.0. Closing for now.
