### ISSUE TITLE
Skipping remote @import of "https://fonts.googleapis.com/css...

### ISSUE THREAD

**Issue by BoilerTom90** [anvilco/spectaql#448]
When I run spectaql, I'm seeing this message in the output:

![image](https://user-images.githubusercontent.com/17208255/182455689-69b3f583-9ea6-4816-b319-bf36ec8cb284.png)

This message shows up even if I use the `--quiet` option.

Spectaql still generates the output, but it would be nice if the root cause of that error could be addressed.

**Comment by newhouse** [comment]
Barlow has been removed from the default theme in 2.0, and can be be turned off via the [`loadExternalFont: false` option](https://github.com/anvilco/spectaql/blob/1.x/config-example.yml#L45) in the latest `1.x` versions.
