### ISSUE TITLE
NPM audit vulnerabilities

### ISSUE THREAD

**Issue by alMWI** [anvilco/spectaql#471]
Hello,

We have an installation of `SpectaQL v1.5.3` in our project. We are seeing some issues when running `npm audit`. It is recommending us to downgrade to `v0.0.2` to fix the vulnerabilities. Currently, there are 11 vulnerabilities listed for SpectaQL.

```
11 vulnerabilities (3 moderate, 6 high, 2 critical)
```

Do you plan on bumping the versions for the dependencies that SpectaQL uses?

Thanks

**Comment by newhouse** [comment]
Hmm. Will have a look.

**Comment by moritz157** [comment]
I just installed SpectaQL on a project of mine and GitHub's dependabot went crazy when I pushed it. So yeah... it would be really great to upgrade some dependencies (the reported vulnerabilites apparently come from `lodash`)

**Comment by moritz157** [comment]
Well nvm my earlier comment - after reading #303 I understand the problem better

**Comment by newhouse** [comment]
> I just installed SpectaQL on a project of mine and GitHub's dependabot went crazy when I pushed it. So yeah... it would be really great to upgrade some dependencies (the reported vulnerabilites apparently come from `lodash`)

Medium term I plan to fork/replicate/replace all the unmaintained junk that has these vulns so that we are squeaky clean at all times.

**Comment by newhouse** [comment]
I am aiming to take care of this in the 2.0 release.

**Comment by knidarkness** [comment]
@newhouse , is there any estimate/timeline for when there's a hope to see v2.0 release?

**Comment by newhouse** [comment]
Aiming for this week @knidarkness

**Comment by newhouse** [comment]
@moritz157 @knidarkness @alMWI All vulnerabilities should now be fixed in `v2`. There are some breaking changes to upgrading, but they should not be too difficult to address.

Closing this for now, but let me know if you have any issues with audits.
