### ISSUE TITLE
Support with Introspection 

### ISSUE THREAD

**Issue by Linuxinet** [anvilco/spectaql#485]
Can this tool works only with Introspection?
I mean I only have Introspection schema how can I specify in the config.yaml to use this tool

**Comment by newhouse** [comment]
Hi @Linuxinet and thanks for using SpectaQL!

You can instruct SpectaQL to build documentation via:
1. Performing an Introspection Query against a live GraphQL server
2. Providing a JSON file that contains the result of an Introspection Query
3. Providing a `.gql` file that contains your GraphQL schema.

It sounds like you're trying to use option 2?

In that case, your configuration yaml file might look like this:
```yml
...

introspection:
  introspectionFile: '/path/to/your/introspection-output.json'
  ...

...
```

You can see (config-example.yml)[https://github.com/anvilco/spectaql/blob/main/config-example.yml] for some more help.
