### ISSUE TITLE
Add ability to specify headers on introspection requests

### ISSUE THREAD

**Issue by benhickson** [anvilco/spectaql#49]
The GraphQL API I'm introspecting requires an API Key to be provided via the request headers. Is there a way to do this currently?

**Comment by benhickson** [comment]
I see there's some options to provide an `Authorization` header, but in our case, we'd need to be able to specify the header key arbitrarily

https://github.com/anvilco/spectaql/blob/8943fe336beb602a6dbc34df9a83e732358f41ed/app/spectaql/graphql-loaders.js#L46-L64

**Comment by newhouse** [comment]
I'd noticed that it was limited support in DociQL, and was waiting for the day when someone asked for more. This makes sense to me and I will add it ASAP.

**Comment by newhouse** [comment]
Added in `v0.2.2` which is now on NPM.
