### ISSUE TITLE
Error when using introspectionFile without specifying a server

### ISSUE THREAD

**Issue by benhickson** [anvilco/spectaql#50]
When no `servers` key is provided in the `config.yml`, but `introspection.url` is used, things work fine. 
However, when I use `introspection.introspectionFile` instead of a URL, I get the error:
```
Must provide Introspection URL
```

When I add a `servers` key, with a server marked as `production`, things work fine.

I think this might be a bug.

This might be section of the code:
https://github.com/anvilco/spectaql/blob/8943fe336beb602a6dbc34df9a83e732358f41ed/app/spectaql/index.js#L106-L113

Or, perhaps I'm misunderstanding the meaning of that error message?

**Comment by newhouse** [comment]
Yeah, this error message is not very helpful at best, and misleading at worst. The components behind its existence seem to be moot:
- they're Swagger related, but do not seem to have any significance from the DociQL world
- they definitely don't have any significance in the SpectaQL enhancement over DociQL.

That being said, until this library officially announces and completes its divorce from Swagger and other legacy things, I'm hesitant to remove the the requirement of something to satisfy the expected components for the Swagger.

So, in the meantime, I think that I'll:
1. Consider another YAML config entry that specifies a "dummy" URL to consider for whatever the Swagger/DociQL stuff might have wanted to do with a URL
2. Give a better error message in any event.

**Comment by newhouse** [comment]
Added in `v0.2.2` which is now on NPM.

**Comment by benhickson** [comment]
nice, thanks!
