### ISSUE TITLE
[Suggestion] Allow graceful parsing of `type` with no fields in static schema file

### ISSUE THREAD

**Issue by ksiopiolosz-vy** [anvilco/spectaql#507]
The following example will cause the parser to throw an exception:

```
// schema.graphql
type MyEmptyType { }
```

Output:
```
Syntax Error: Expected Name, found "}".
```

We have restrictions on fields we'd like to show externally, so having the option to ignore empty types would be great.

**Comment by newhouse** [comment]
That error is almost certainly coming directly from `graphql-tools`, which parses the SDL to generate your schema. Having an empty Type with no fields is invalid, apparently. Unless there's an option for `graphql-tools` that I can pass to allow empty types, then there's nothing I can do I'm afraid.

However:
> We have restrictions on fields we'd like to show externally, so having the option to ignore empty types would be great.

Hiding Types, Fields, Arguments, Queries, Mutations, etc, is a big part of what SpectaQL is good at providing for you. You can provide SpectaQL with metadata that indicates if something should be hidden or not. There are several ways to provide this information, but perhaps you might like to use the `@spectaql` directive in your SDL to indicate that a field should be hidden?

See the [metadata](https://github.com/anvilco/spectaql#metadata) area for more info.

There are also a number of config options in [this area](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L220) that you may find helpful, but I think you'll want to use the metadata approach.

Going to close for now, but let me know if this helps you out.
