### ISSUE TITLE
Proposal: Remove remote import from Google Fonts for GDPR compliance

### ISSUE THREAD

**Issue by moritz157** [anvilco/spectaql#508]
SpectaQL currently imports the Barlow font directly from Google servers when using the default theme. 
However, without explicitly asking for the user's consent, this is considered to violate the General Data Protection Act (GDPR) and therefore makes the default theme not usable in EU member states. (Source: https://cookie-script.com/blog/google-fonts-and-gdpr)

Although users of SpectaQL could simply create their own theme and omit the remote import, I think this really creates a potential for some to publish a non GDPR-compliant documentation and receive fines for it.

I would propose to simply include the font in SpectaQL (as long as the license allows it) to solve this issue for all of us europeans.

**Comment by newhouse** [comment]
This is now possible by setting the `spectaql.loadExternalFont` config option to `false`.

Released in `v1.5.8`!
