### ISSUE TITLE
spectaQL directive breaks the GQL server when it's not defined

### ISSUE THREAD

**Issue by jason-dahl** [anvilco/spectaql#545]
I'm trying to implement spectaQL for our orgs graphql server.  I'm having quite a bit of trouble with getting any approach to adding metadata in.  My preferred method would be to use the spectaQL directive as then I can add my documentation right in my schema, but the part I'm not understanding is that adding an undefined directive to your schema will break the server

```
/opt/myorg/node_modules/graphql/validation/validate.js:108
    throw new Error(errors.map(function (error) {
          ^
Error: Unknown directive "spectaql".

Unknown directive "spectaql".
    at assertValidSDL (/opt/myorg/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/opt/myorg/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/opt/myorg/node_modules/apollo-server-express/node_modules/graphql-tools/src/generate/buildSchemaFromTypeDefinitions.ts:43:32)
    at Object.makeExecutableSchema (/opt/myorg/node_modules/apollo-server-express/node_modules/graphql-tools/src/makeExecutableSchema.ts:52:16)
    at ApolloServer.initSchema (/opt/myorg/node_modules/apollo-server-express/node_modules/apollo-server-core/src/ApolloServer.ts:493:27)
    at new ApolloServerBase (/opt/myorg/node_modules/apollo-server-express/node_modules/apollo-server-core/src/ApolloServer.ts:356:26)
    at new ApolloServer (/opt/myorg/node_modules/apollo-server-express/src/ApolloServer.ts:88:5)
    at Object.<anonymous> (/opt/myorg/app/src/index.ts:122:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/opt/myorg/node_modules/ts-node/src/index.ts:858:23)
[nodemon] app crashed - waiting for file changes before starting...
```

I've tried defining the directive in my schema as well:
```
    input SpectaQLOption {
        key: String!
        value: String!
    }
    directive @spectaql(options: [SpectaQLOption]) on FIELD_DEFINITION
```

and this also doesn't seem to get picked up when running spectaql.  This is how I'm using the directive

```
    """this is documented"""
    type MyType {
        myField: String! @spectaql(options: [{ key: "example", value: "it looks like this" }]. # this is not generating anything with spectaQL)
        "this is anotherfield, which is documented and picked up by spectaQL"
        anotherField: String!
    }
```

The spectaQL docs say that it's unnecessary to define the directive yourself, so I'm quite lost as to how that's possible.  As well as to why spectaQL isn't picking up on the directive once it's defined.

**Comment by jason-dahl** [comment]
I've been poking around this project and it looks like it's almost intended to download your schema, then run spectaQL, where as the approach I want to go is use the `url` option for introspection and actually hit my gql server.  If that's the case, am I able to add metadata + examples in my outputted documentation?

**Comment by newhouse** [comment]
Hi @jason-dahl I understand the use-case here and will have a look ASAP. I'm surprised to hear it's not having an effect when you define the directive yourself in your SDL, but I'll figure it out and get back to you.

**Comment by newhouse** [comment]
Ah yes, upon re-reading your use-case, this is unfortunately not possible right now via the introspection query. The problem is that the introspection query does not (in the spec) expose what directives are applied to what things.

The best thing for you to do is to somehow get your SDL file (with the directives throughout) downloaded to SpectaQL for use. Sorry!

**Comment by elijaholmos** [comment]
I'm running into a similar issue with a schema-first approach. My `schema.graphql` file contains several `@spectaql` directives, but when I try to use it to create a GQL api with Nest.js and Apollo, I get several `Unknown directive "@spectaql".` errors as the Nest.js application attempts to spin up.

When I use the `spectaql` package to generate my GQL documentation, I instruct it to pull from my local `schema.graphql` file, so unlike the original use case of this issue, I'm not hitting a server to retrieve my schema. What options do I have?

**Comment by elijaholmos** [comment]
@newhouse the first suggestion worked, thank you 🙂 I like how it can be done programmatically for my SDL generation, and I may use that as my project progresses. thank you for the help.
