### ISSUE TITLE
Ability to override defaults via YAML

### ISSUE THREAD

**Issue by fileformat** [anvilco/spectaql#57]
Currently, options that have [defaults](https://github.com/anvilco/spectaql/blob/54b51c591c59857341d87b0c36175d610a27445a/app/index.js#L21) cannot be specified in the YAML file.  For example: `oneFile` only works when specified on the command line.

This is caused by the using [_.extend() with the defaults](https://github.com/anvilco/spectaql/blob/54b51c591c59857341d87b0c36175d610a27445a/app/index.js#L94) before using [_.defaults() with the YAML](https://github.com/anvilco/spectaql/blob/54b51c591c59857341d87b0c36175d610a27445a/app/index.js#L115).

I think it would be a simple fix to move the _.extend() to after the _.defaults() (say, around line 130).  If this sounds right/acceptable, I can submit a PR.

**Comment by newhouse** [comment]
Ah yes, this is not cool. Fixing in https://github.com/anvilco/spectaql/pull/61

**Comment by newhouse** [comment]
This is fixed in `main` and was published in `0.2.3`...thanks!
