### ISSUE TITLE
Example Documentation not generating

### ISSUE THREAD

**Issue by vecchp** [anvilco/spectaql#6]
I seem to be unable to generate the example documentation.

The following commands produce the same error:

```
➜  examples git:(main) ✗ npx spectaql config.yml
Unexpected token '.'
```

```
➜  spectaql git:(main) ✗ npx spectaql ./examples/config.yml
Unexpected token '.'
```

Am I missing an obvious step here?

**Comment by vecchp** [comment]
Seems like it might be related to having an older version of node: https://stackoverflow.com/questions/63775130/unexpected-token-when-using-optional-chaning-syntax-when-running-mocha

**Comment by newhouse** [comment]
Hi @vecchp - that's very strange. No stack trace whatsoever?

> Seems like it might be related to having an older version of node: https://stackoverflow.com/questions/63775130/unexpected-token-when-using-optional-chaning-syntax-when-running-mocha

Ah yes, I think there are perhaps some things that are incompatible with older versions of Node, despite the `engines` specifying `>=8` in the `package.json`.

What version of node are you running? I should harden this for `8` better, either by re-writing some things or by babelizing stuff with an `8` target.

**Comment by newhouse** [comment]
Very sorry for this bug. in the meantime, as a workaround, you could consider using [NVM](https://github.com/nvm-sh/nvm) and adding Node 14 via `nvm install 14` (or `nvm install 14.X.Y`), installing and running it while using that engine.

**Comment by newhouse** [comment]
Just published `v0.0.6` which should get you going again on the global installation side of things. You'll need to update your global installation via `npm update -g spectaql` (or similar).

**Comment by vecchp** [comment]
> Hi @vecchp - that's very strange. No stack trace whatsoever?
> 
> > Seems like it might be related to having an older version of node: https://stackoverflow.com/questions/63775130/unexpected-token-when-using-optional-chaning-syntax-when-running-mocha
> 
> Ah yes, I think there are perhaps some things that are incompatible with older versions of Node, despite the `engines` specifying `>=8` in the `package.json`.
> 
> What version of node are you running? I should harden this for `8` better, either by re-writing some things or by babelizing stuff with an `8` target.

We were running node 12.

**Comment by newhouse** [comment]
Optional Chaining seemed to have been the only culprit, and that's only been supported since [Node 14.0.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

Should be all set with latest version.
