### ISSUE TITLE
can schemaFile config option take in an array and not just one path?

### ISSUE THREAD

**Issue by ahmetthepoet** [anvilco/spectaql#65]
Hello, I was wondering if it would make sense  to allow spectaql take in multiple schemaFiles. I had to split my schema into multiple files because it was getting to long but this now means I cant use spectaql to scrape the schema to generate the static pages

**Comment by newhouse** [comment]
Hi @ahmetthepoet and thanks for using SpectaQL!

This is a good idea that falls in line with how GraphQL is used and developed...I've gone ahead and done the work already:
https://github.com/anvilco/spectaql/pull/69

Once that gets merged, I'll publish it and circle-back here.

**Comment by newhouse** [comment]
Published in version `0.3.1`

**Comment by ahmetthepoet** [comment]
Thanks @newhouse tested it out and it works like a charm!
