### ISSUE TITLE
Specify custom images path

### ISSUE THREAD

**Issue by adriantr** [anvilco/spectaql#691]
We have a need where we want to adjust href of favicon and logo adding additional prefix e.g. from `images/logo.png` to `docs/images/logo.png`.

**Comment by newhouse** [comment]
Are you saying that you will not be providing a local file to SpectaQL, but would rather prefer to provide a (relative) URL path instead?

If so, I understand, and I would probably implement it as a new configuration option named `logoUrl` (and `faviconUrl`) under the `spectaql` group. If you follow around the `logoFile` and `faviconFile` references, it's probably pretty easy to accommodate what you're trying to do.

If you can't figure it out, I'll get to it eventually next round of enhancements.

Good luck!
