### ISSUE TITLE
npm install fails with error

### ISSUE THREAD

**Issue by the-mellema** [anvilco/spectaql#732]
I cloned down the spectaql repo and ran the npm install command. Here's the error I get:

walker$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: spectaql@2.0.4
npm ERR! Found: eslint@8.34.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.10.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.12.1" from eslint-config-standard@16.0.3
npm ERR! node_modules/eslint-config-standard
npm ERR!   dev eslint-config-standard@"^16.0.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry

**Comment by newhouse** [comment]
@the-mellema Thanks for pointing this out. I this is due to differences between how `npm` and `yarn` (which I mainly use) will handle resolving dependencies. I just pushed an update to `main` that should fix this for `npm` users like you. Can you pull the latest and try it now?

**Comment by the-mellema** [comment]
Yes that resolved the issue. Thanks!
