### ISSUE TITLE
Question: can I add extra sections?

### ISSUE THREAD

**Issue by zippocage** [anvilco/spectaql#778]
Is it possible to add new sections to the generated documentation? If yes, what formats are possible to use (e.g. markup)?

Rationale:
We want to add free text that explains the overall API. It may be a number of paragraphs and does not belong to a specific type or operation in the schema.

**Comment by newhouse** [comment]
Hello @zippocage and thanks for using SpectaQL!

I think that the easiest way you might be able to accomplish what you're looking for is via the "intro items" in the `config.yml`.

This area here: https://github.com/anvilco/spectaql/blob/main/config-example.yml#L414

You can "in-line" it in the config, or you can point to a separate Markdown file.

Does this work for you?

**Comment by zippocage** [comment]
Tried it now, works great!
