### ISSUE TITLE
Access data rather than rendered HTML

### ISSUE THREAD

**Issue by timmyg** [anvilco/spectaql#847]
Hi, we are trying to write a completely custom frontend and was wondering if there was any way to tap into just the data object that is created to generate the html?

**Comment by timmyg** [comment]
Looking like `loadData` is what I want

**Comment by timmyg** [comment]
This is working for me:
```
const { loadData, resolveOptions } = require('spectaql');
await loadData(resolveOptions(spectaqlOptions));
```

**Comment by newhouse** [comment]
> Hi, we are trying to write a completely custom frontend and was wondering if there was any way to tap into just the data object that is created to generate the html?

Out of curiosity, can you provide some more context? You just like all the stuff that SpectaQL does regarding organization, converting to objects, metadata, etc, but you'd like to just do the HTML part yourself? Would love to hear what you like and don't like about the library, but you are of course welcome to use it however you see fit!
