### ISSUE TITLE
SDL Directive not respecting `undocumented: true` on ENUM_VALUE

### ISSUE THREAD

**Issue by SympleSynz** [anvilco/spectaql#855]
Following the examples in the readme and documentation, I attempted to add the directive
`@spectaql(options: [{ key: "undocumented", value: "true" }])`
to an ENUM_VALUE that we use internally for testing but don't want in our public documentation

We found that the above directive does work on the whole ENUM type, but we are unable to have it apply to a specific ENUM_VALUE

**Comment by SympleSynz** [comment]
I'm not following the code super well, but I'm wondering if this is a quick fix to add `ENUM_VALUE` logic to [spectaql](https://github.com/anvilco/spectaql/tree/main)/[src](https://github.com/anvilco/spectaql/tree/main/src)/[spectaql](https://github.com/anvilco/spectaql/tree/main/src/spectaql)/[augmenters.js](https://github.com/anvilco/spectaql/tree/main/src/spectaql/augmenters.js) `func hideFields` on line 154

**Comment by newhouse** [comment]
This should be fixed in the latest `main`, as well as in `spectaql@2.2.0-beta.0`.

There is a dependency with a busted semver that I'm waiting for them to resolve before publishing completely as `2.2.0`.

Can you confirm this works?

@SympleSynz

**Comment by SympleSynz** [comment]
Thank you very much for the fix. I'll pull it in and give it a test this coming week

**Comment by SympleSynz** [comment]
@newhouse Confirmed that the above version worked and removed the `ENUM_VALUE` we didn't want published
