### ISSUE TITLE
Proper JSON-representation of JSON example

### ISSUE THREAD

**Issue by newhouse** [anvilco/spectaql#87]
The values in the below example object should all have quotes around them...

![image](https://user-images.githubusercontent.com/2524009/129575441-7e8d5913-2054-447d-9db3-21de8d8a5629.png)

**Comment by louisa-ba** [comment]
I would like to see this too

**Comment by louisa-ba** [comment]
I made a PR for graphql-scalars you could do something similar for Apollo Upload. https://github.com/anvilco/spectaql/pull/176/files

**Comment by newhouse** [comment]
This has been fixed.
