### ISSUE TITLE
Support linking to other objects in the doc

### ISSUE THREAD

**Issue by benogle** [anvilco/spectaql#89]
I'd like to be able to add syntax to descriptions of objects, resolvers, args, etc that links to other objects in the reference. e.g.

```
This object connects a {{User}} to an {{Organization}}.
```

Then have `User` and `Organization` create links to the respective objects. 

Not sure on syntax, but it'd be nice to be able to link to anything: queries, mutations, or types like this

**Comment by newhouse** [comment]
I like this idea a lot...will look into it. Thanks!

**Comment by newhouse** [comment]
Due to some limitations and anticipated use cases, I had to keep it somewhat rugged and it will only return an anchor link for the specified thing...you'll have to get a little more down and dirty, typically by building a markdown link yourself, but it allows for more flexibility.
