### ISSUE TITLE
Adding Types to documentation only if they are used by a documented operation

### ISSUE THREAD

**Issue by nivo33** [anvilco/spectaql#90]
Hi,

First an explanation of my use-case:
I have a large GraphQL API, and I am only interested in exposing very few queries and mutations. With the current set up, it requires a lot of manual work:
1) I must turn everything off by default.
2) Turn on the mutations and queries I want to document (with {documented: true})
Until here, no problem. This is the amount of work I expected.

The problem starts with the next step:
3) Understand all the return types and input types for each of these mutations and queries and turn them on in the same manner individually <- This is a lot of work!

I've made changes locally that allow for a new option `typeDocumentedOnlyIfPartOfDocumentedQueryOrMuatation`, that if set to `true`, will automatically recurse mutations and queries with `documented` set to true and document ONLY the types associated with those queries and mutations (either as InputTypes or as return Types).

This allows a user to simply say what queries and mutations he wants documented, and the rest happens automatically.

I'd be happy to open a PR for this, but this is my first time contributing so I wanted to make sure if thats OK ✌️ 

Thanks

**Comment by newhouse** [comment]
Hi @nivo33 and thanks for using SpectaQL!

I think I understand your usecase and what you're saying. Currently, SpectaQL should "hide" fields from Types if the field's return Type is not documented...but it does not "hide" Types that are not part of any Query or Mutation. This is what you're asking for, yes?

I see the algorithm as:
1. Hide all the things that should be explicitly hidden based on metadata or options. This is currently happening already in [this area](https://github.com/anvilco/spectaql/blob/main/app/spectaql/augmenters.js#L314).
2. Take another pass where you go through each Query and Mutation, then recurse/loop through the following to amass a set of "used" Types:
   1. The Query and Mutation Arguments to get all the Types...then recurse down that Type's Fields (and any Arguments of those Fields) to get all "used" Types.
   2. The Query and Mutation return Types..then recurse down that Type's Fields (and any Arguments of those Fields) to get all "used" Types.
3. Go through the Types and hide all the ones that are not in that set of "used" Types.

If I were going to develop this, I'd:
1) Add an option like `hideUnusedTypes` to the [YAML](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L169).
2) Add a function at the end of [these `hideXXX(...)`](https://github.com/anvilco/spectaql/blob/main/app/spectaql/augmenters.js#L314) that goes through the algorithm described above, if the option says to do so.

I'm planning on working on a few bugs and enhancements this week or next, so maybe give me a few days to circle back here with updates before you start working on it? Or if you want to share a branch/PR from your fork as food for thought, that'd be much appreciated!!

**Comment by newhouse** [comment]
> Or if you want to share a branch/PR from your fork as food for thought, that'd be much appreciated!!

Looks like you already opened one, thanks! I'll have a look!

**Comment by nivo33** [comment]
I think I pretty much did it the way you mentioned.
Looking forward to your comments and suggestions 😄

**Comment by newhouse** [comment]
@nivo33 thank you very much for your PR and interest in SpectaQL. As I've mentioned around, I'm nearly done with a big re-write of SpectaQL that will include this capability, so I'm going to close this.

Thank you for your effort though!
