### ISSUE TITLE
Samples request and response for generated query/mutations

### ISSUE THREAD

**Issue by Shreyas-vgr** [anvilco/spectaql#901]
What's the standard practice/recommendations to add sample request&responses to document generated queries from a specific schema using spectaql.
Are there any reference examples I can look at?

**Comment by newhouse** [comment]
Hello @Shreyas-vgr and thanks for using SpectaQL!

Can you be more specific? There are already GraphQL query/mutation request examples, as well as a JSON representation of the expected response that will be displayed in the HTML output.

Are you talking about a CURL-type sample, or what do you mean?

**Comment by Shreyas-vgr** [comment]
>There are already GraphQL query/mutation request examples, as well as a JSON representation of the expected response that will be displayed in the HTML output.

can you share the link ? Are there any guide on how to customize these request examples (JSON representation)

**Comment by Shreyas-vgr** [comment]
@newhouse any update on this?

**Comment by newhouse** [comment]
Hi @Shreyas-vgr 

While a bit rough around the edges, all the customization of the request and response JSON is possible by one of these methods:
1. (preferable) Providing "metadata" to SpectaQL that includes appropriate `example` values. That approach is discussed [here](https://github.com/anvilco/spectaql#metadata) in the README.
2. (alternative) Providing a Dynamic Example Generator module to SpectaQL that will be used to generate examples on the fly. That approach is discussed [here](https://github.com/anvilco/spectaql#dynamic-example-generators) in the README.

I'm going to close this for now as anything else you might mean is not currently supported.
