### ISSUE TITLE
Documentation for interfaces

### ISSUE THREAD

**Issue by trevorr** [anvilco/spectaql#92]
Spectaql doesn't seem to generate output for interface types or queries that return them. In other words, I see my types that are declared as `type` or `input` but not `interface`, and queries that return interface types don't show up at all. I don't see any mention of interfaces in the documentation, so maybe they're not currently supported? What would be required to include these in the documentation?

**Comment by newhouse** [comment]
Fix coming...

**Comment by newhouse** [comment]
Fixed in `0.8.0`

**Comment by Matovidlo** [comment]
I am currently using version `1.2.1` and the interfaces are not generated. Back in version `0.9.2` it is wroking correctly. Can you please fix it as before? The documentation then have not working links to the interfaces and people complain about not working links. Either remove it from docs or fix the links and generation of interfaces. Thank you in advance
