### ISSUE TITLE
grunt-contrib-jshint seems unused

### ISSUE THREAD

**Issue by mscolnick** [anvilco/spectaql#93]
Could we remove `grunt-contrib-jshint` from the `package.json` since it looks unused? This currently causes issues with `jshint` in a [Bazel monorepo](https://github.com/bazelbuild/rules_nodejs/issues/1632) which has non-ideal workarounds.

**Comment by newhouse** [comment]
Sure, I don't see why not...

**Comment by newhouse** [comment]
Published in `0.6.3` just now

**Comment by mscolnick** [comment]
thank you!
